### PR TITLE
Addition of The Swift Code Review Podcast

### PR DESCRIPTION
**Pull request by jeffreyfultonca**
Addition of The Swift Code Review Podcast: In-depth technical analysis of Swift code discussing pros and cons as they relate to iOS and Server-Side Swift development.

### CODE REVIEW

**Comment by vermont42** [comment]
Thanks for the PR! I recreated it in my own commit because I am a fussbudget about commit-message wording and capitalization.

I look forward to using [Snow Your Zone](https://jeffreyfulton.ca/snowyourzone) when parking in Winnipeg during the winter.

**Comment by jeffreyfultonca** [comment]
Thanks! I appreciate your corrections to the show's description text. I actually just updated the website and rss feed to match.

What's this about you visiting Winnipeg? Do you actually have a connection to Winnipeg or are you just being nice?

**Comment by vermont42** [comment]
Kidding, but I am a fan of Canada. Rush, John Candy, poutine, etc.

**Comment by jeffreyfultonca** [comment]
You got me!

I'm a fan of Duke Caboom.
DukeCaboomFull JPG

**Pull request closed without merging**
